# Generated by Django 5.1 on 2024-10-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_feedback_date_alter_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
    ]
