# Generated by Django 5.1 on 2024-10-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_feedback_bill_details_review_bill_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='BILL_DETAILS',
            new_name='BILL_DETAIL',
        ),
    ]
