# Generated by Django 5.1 on 2024-10-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_bill_detail_feedback_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='BILL_DETAILS',
            new_name='ORDER',
        ),
    ]
