# Generated by Django 5.1 on 2024-10-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_bill_details_review_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
    ]
