# Generated by Django 5.1 on 2024-10-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_details',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
