# Generated by Django 5.1 on 2024-10-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_offlinepurchaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepurchaser',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
